version: '3.9'

services:
  go-app:
    container_name: go-app
    # image: francescoxx/go-app:1.0.1
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:5050"
    depends_on:
      - go_db

volumes:
  pgdata: {}
